# .golangci.yml
version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
  settings:
    errcheck:
      check-blank: true
    govet:
      enable:
        - shadow
    gosec:
      excludes:
        - G104 # Duplicates errcheck
        - G304 # File path from variable (expected in CLI)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      # Examples prioritize readability over exhaustive error handling
      - path: ^examples/
        linters:
          - errcheck

run:
  timeout: 5m
  tests: true

issues:
  max-same-issues: 0
